### PR TITLE
Work in progress

### PR DESCRIPTION
**Pull request by IsmailM**

### CODE REVIEW

**Comment by IsmailM** [comment]
the tests expect GV to be installed - might be best to install GV as well in travis?

**Comment by yeban** [comment]
The last change was 5 days ago. Is it up to date?

**Comment by IsmailM** [comment]
It's fully working inside GV...

The only remaining thing I was planning to do was add a sed line in Travis `before_install` to add GV as a dependency in the gemspec to fix the failing tests...

**Comment by IsmailM** [comment]
This is a lower priority at the moment - will give you a shout when I think it would be useful for you review it 👍

**Pull request merged**
